In [1]:
#importing packages
import numpy as np
import pandas as pd
df=pd.read_excel("ML_ASSIGNMENT.xlsx")
print(df)


        age  income student credit_rating buys_computer
0      <=30    high      no          fair            no
1      <=30    high      no     excellent            no
2   31...40    high      no          fair           yes
3       >40  medium      no          fair           yes
4       >40     low     yes          fair           yes
5       >40     low     yes     excellent            no
6   31...40     low     yes     excellent           yes
7      <=30  medium      no          fair            no
8      <=30     low     yes          fair           yes
9       >40  medium     yes          fair           yes
10     <=30  medium     yes     excellent           yes
11  31...40  medium      no     excellent           yes
12  31...40    high     yes          fair           yes
13      >40  medium      no     excellent            no


In [16]:
df_income = pd.get_dummies(df['income'])
df_student = pd.get_dummies(df['student'])
df_new = pd.concat([df,df_income,df_student], axis=1)
print(df_new)



        age  income student credit_rating buys_computer  high  low  medium  \
0      <=30    high      no          fair            no     1    0       0   
1      <=30    high      no     excellent            no     1    0       0   
2   31...40    high      no          fair           yes     1    0       0   
3       >40  medium      no          fair           yes     0    0       1   
4       >40     low     yes          fair           yes     0    1       0   
5       >40     low     yes     excellent            no     0    1       0   
6   31...40     low     yes     excellent           yes     0    1       0   
7      <=30  medium      no          fair            no     0    0       1   
8      <=30     low     yes          fair           yes     0    1       0   
9       >40  medium     yes          fair           yes     0    0       1   
10     <=30  medium     yes     excellent           yes     0    0       1   
11  31...40  medium      no     excellent           yes     0   

In [17]:
from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier

from sklearn import metrics

import pandas as pd



# Split dataset into features and target variable

feature_cols = ['age', 'income', 'credit_rating', 'buys_computer']

X = pd.get_dummies(df[feature_cols[:-1]], columns=['age', 'credit_rating','income'], drop_first=True)

Y = df['student']



# Split dataset into training set and test set

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=1)  # 70% training and 30% test



# Create a Decision Tree classifier object

model = DecisionTreeClassifier()



# Train the Decision Tree classifier

model.fit(X_train, Y_train)



# Calculate the Training Set accuracy

tr_accuracy = model.score(X_train, Y_train)

print("Accuracy:", tr_accuracy)



# Get the depth of the Decision Tree

depth = model.get_depth()

print("Tree Depth:", depth)

Accuracy: 1.0
Tree Depth: 3


In [12]:
from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier

from sklearn import metrics



# Split dataset into features and target variable

feature_cols = ['age', 'income', 'credit_rating', 'buys_computer']

X = pd.get_dummies(df[feature_cols[:-1]], columns=['age', 'credit_rating','income', 'credit_rating'], drop_first=True)

Y = df['buys_computer']





# Split dataset into training set and test set

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=1)  # 70% training and 30% test



# Create Decision Tree classifier object

clf = DecisionTreeClassifier()



# Train Decision Tree Classifier

clf = clf.fit(X_train, Y_train)



# Predict the response for the test dataset

y_pred = clf.predict(X_test)



# Model Accuracy, how often is the classifier correct?

print("Accuracy:", metrics.accuracy_score(Y_test, y_pred))

Accuracy: 0.8


In [22]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder()
#transform data
X = encoder.fit_transform(df)
print(X)

[[1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1.]
 [2. 2. 0. 1. 1.]
 [2. 1. 1. 1. 1.]
 [2. 1. 1. 0. 0.]
 [0. 1. 1. 0. 1.]
 [1. 2. 0. 1. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 1. 1. 1.]
 [1. 2. 1. 0. 1.]
 [0. 2. 0. 0. 1.]
 [0. 0. 1. 1. 1.]
 [2. 2. 0. 0. 0.]]


In [25]:
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier, plot_tree
plt.figure(figsize=(12, 8))

plot_tree(model, filled=True, feature_names=X.columns, class_names=['No', 'Yes'])

plt.show()

AttributeError: ignored

<Figure size 1200x800 with 0 Axes>

In [23]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=1)  # 70% training and 30% test
